### ISSUE TITLE
Remove FullStackRustDemo

### ISSUE THREAD

**Issue by hgzimmerman** [jetli/awesome-yew#2]
Its a old, bloated, and dead project of mine. Its very unfinished and is very outdated.

I've re-implemented a smaller subsection of it here: https://github.com/hgzimmerman/BucketQuestions

Its not done here either, but I do intend to complete it eventually, and it is currently up to date with the current release of Yew.

**Comment by jetli** [comment]
Removed, replace with BucketQuestions repo
