### ISSUE TITLE
Daisy UI library

### ISSUE THREAD

**Issue by kunjee17** [jetli/awesome-yew#35]
My company is working on product and we are trying out yew. In a process we are abstracting DaisyUI (tailwindcss based) library. It is very much early but if that is OK (with WIP tag) then please add it. [TailYew](https://github.com/fuzzycloud/tailyew). 

Currently DaisyUI and Heroicons are there and in future we are planning to add more Ui components there. Any help/ suggestions are also very much welcome.

**Comment by jetli** [comment]
fixed, thanks
